version: "3.9"

services:
  web:
    build: .
    container_name: bacon_flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./app/backend/data:/app/app/backend/data
    environment:
      - FLASK_ENV=development